### ISSUE TITLE
how to launch ?

### ISSUE THREAD

**Issue by havena** [Bannerlord-Community-Mods/TestGameMode#1]
hi @gallexme, just a little question.
I fix it from beta to EA, but i dont know how to launch PeaceGameMode in EA. cant find it in custom battle config or somewhere. 

i try a lot of thing on OnSubModuleLoad after this, but cant find how to start a "game"
`  Module.CurrentModule.AddMultiplayerGameMode(new PeaceMissionBasedMultiplayerGamemode("PeaceGameMode"));
Module.CurrentModule.GetMultiplayerGameTypes().First(x => x.GameType == "PeaceGameMode").Scenes.Add("mp_tdm_map_001_spring");`

can u help me?

**Comment by gallexme** [comment]
its a Multiplayer Gamemode, u set it in Host Games option then Launch it

https://media.discordapp.net/attachments/677511186295685150/692737478062374942/unknown.png
https://cdn.discordapp.com/attachments/677511186295685150/692737363025330316/unknown.png
https://media.discordapp.net/attachments/682890294873817171/693497501885661254/unknown.png?width=722&height=915


@havena

**Comment by havena** [comment]
how to open this hostgames menu ? with a mod?
@gallexme

**Comment by gallexme** [comment]
with the community launcher you can join a community lobbyserver and open the menu in normal server browser, but u would need permissions for it
also the hosting feature has been removed in 0.9, noone would be able to join you, gotta wait for dedicated server filesmaybe have a look at the offline mp mod and use it + join official tw servers
then u can host offline only with f5

prolly doesnt work in 1.0+ anymore tho

[offlinemultiplayer.2.zip](https://github.com/Bannerlord-Community-Mods/TestGameMode/files/4469112/offlinemultiplayer.2.zip)

**Comment by havena** [comment]
thx a lot. how to request apply for community lobbyserver ?

**Comment by ffinkdevs** [comment]
Just give me  64 character long steam id and I'll add you, the permission
thing doesn't matter anymore anyways since hosting broke Completly

https://discord.gg/2pVSNJ
And u can reach  us here

**Comment by havena** [comment]
76561197971054451
